POST http://localhost:1323/insertANewMahasiswa
Content-Type: application/json

{
    "nama": "B",
    "usia": 3,
    "gender": 1,
    "nama_semua_jurusan": ["teknik kelautan", "teknik industri"],
    "nama_semua_hobi":["basket","futsal"]
}

###
POST  http://localhost:1323/updateAMahasiswa?id=2
Content-Type: application/json

{
    "nama": "update",
    "usia": 200,
    "gender": 0
}

###
GET http://localhost:1323/getAllMahasiswa
Content-Type: application/json

###
GET http://localhost:1323/getAMahasiswa?id=2
Content-Type: application/json

###
DELETE  http://localhost:1323/deleteAMahasiswa?id=1
Content-Type: application/json


